basic-recompile:
	echo "STARTING COMPILE&RUN" && ./gradlew run
fresh-build:
	echo "STARTING GEN.SH" && ./gen.sh && echo "STARTING PRECOMMIT" && ./precommit.sh && echo "STARTING COMPILE&RUN" && ./gradlew run
