/*
 * DO NOT EDIT THIS FILE DIRECTLY
 * Edit the source file at `./gatsby/src/gatsby-node.ts`
 */

require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`,
});

module.exports = require('./gatsby/.gatsby/gatsby-config').default;
