/**
 * Implement Gatsby's Node APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/node-apis/
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Edit the source file at `./gatsby/src/gatsby-node.ts`
 */

module.exports = require('./gatsby/.gatsby/gatsby-node').default;
